/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
   {type: 'autogenerated', dirName: '.'},
      {
      type: "category",
      label: "使用教程",
      collapsible: false,
      items: [
        {
          type: "link",
          label: "编写并运行 C++ 程序", // 链接标签
          href: "https://1024code.com/codecubes/gkRjPRW", // 外部 URL
        },
        {
          type: "link",
          label: "编写并运行 Java Web 项目", // 链接标签
          href: "https://1024code.com/codecubes/ptOy9Om", // 外部 URL
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
